[project]
name = "optimal-path-ec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.24.4",
    "opencv-python>=4.11.0.86",
]

[project.scripts]
optimal_path_ec = "optimal_path_ec.__main__:main"