random_seed:
    uniform: 123
    norm: 456
    map_seed: 333
map:
    frameSize: (500, 500)
    borderWidth: 10
    max_points: 20
    min_dist: 100
    max_range: 400
    min_angle_degrees: 30
    expand_width: 20

model:
    d: 10

ec:
    population: 30
    generation: 15
    crossoverFraction: 1.0